version: '3'
services:
  app:
    container_name: benton-shop-backend
    restart: always
    build: .
    ports:
      - '80:3000'
    depends_on:
    - mongo
  mongo:
    container_name: benton-shop-db
    image: mongo
    ports:
      - '27017:27017'